package tetris;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Davi Campolina
 */
public class PlacarDeLideres extends javax.swing.JFrame {
    
    private DefaultTableModel tm;
    private final String PLACAR_LIDERES = "placarLideres";
    private TableRowSorter<TableModel> ordenador;

    /**
     * Creates new form PlacarDeLideres
     */
    public PlacarDeLideres() {
        
        initComponents();
        
        try {
            
            this.iniciaTabela();
            
        } catch (Exception e) {
            
            System.err.println(e.getMessage());
            
        }
        
        this.iniciaOrdenadorDeTabela();
        
    }
    
    private void iniciaTabela () throws FileNotFoundException {
        
        Vector<String> ci = new Vector<String>();
        ci.add("NOME");
        ci.add("PONTUAÇÃO");
        
        tm = (DefaultTableModel) this.placarLideres.getModel();
        
        try {
            
            ObjectInputStream os;
            
            try (FileInputStream fis = new FileInputStream(new File ("data" + File.separator + PLACAR_LIDERES + ".bin"))) {
                
                os = new ObjectInputStream(fis);
                tm.setDataVector((Vector<Vector>)os.readObject(), ci);
                
            }
            
            os.close();
            
        } catch (Exception e) {
            
            System.err.println(e.getMessage());
            
        }
        
    }
    
    private void iniciaOrdenadorDeTabela () {
        
        this.ordenador = new TableRowSorter<>(this.tm);
        this.placarLideres.setRowSorter(ordenador);
        
        List<SortKey> chave = new ArrayList<>();
        chave.add(new SortKey(1, SortOrder.DESCENDING));
        
        ordenador.setSortKeys(chave);
        
    }
    
    private void salvar () {
        
        try {
            
            ObjectOutputStream os;
            
            try (FileOutputStream fos = new FileOutputStream(new File ("C:\\Users\\Davi Campolina\\Documents\\Workspace\\MY_PROJECTS\\TETRIS\\data\\" + PLACAR_LIDERES + ".bin"))) {
                
                os = new ObjectOutputStream(fos);
                os.writeObject(tm.getDataVector());
                
            }
            
            os.close();
            
        } catch (Exception e) {
            
            System.err.println(e.getMessage());
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        placarLideres = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botaoMenu.setFont(new java.awt.Font("Monocraft", 0, 12)); // NOI18N
        botaoMenu.setText("Menu Principal");
        botaoMenu.setFocusable(false);
        botaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuActionPerformed(evt);
            }
        });

        placarLideres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "PONTUAÇÃO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        placarLideres.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(placarLideres);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoMenu)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoMenu)
                .addGap(5, 5, 5))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuActionPerformed
        
        this.setVisible(Boolean.FALSE);
        TETRIS.mostraInicio();
        
    }//GEN-LAST:event_botaoMenuActionPerformed

    public void adicionaNome (String nomeJogador, Integer pontos) {
        
        this.tm.addRow(new Object[] {nomeJogador, pontos});
        this.ordenador.sort();
        this.salvar();
        this.setVisible(Boolean.TRUE);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacarDeLideres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacarDeLideres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacarDeLideres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacarDeLideres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacarDeLideres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable placarLideres;
    // End of variables declaration//GEN-END:variables
}
